name: Deploy Git-Action-Flow

on:
  push:
    branches:
      - git-action-flow-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Set up Node.js
      uses: actions/setup-node@v2 
      with:
        node-version: '20'  # Upgrade to Node.js 20
    
    - name: Configure Git
      run: |
        git config --global user.email "ls125@rice.edu"
        git config --global user.name "Linshengyi-William"

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages-git-action-flow
        FOLDER: build