name: Deploy Git-Action-Flow

on:
  push:
    branches:
      - git-action-flow-deploy

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Upgrade to Node.js 16
    
    - name: Configure Git
      run: |
        git config --global user.email "ls125@rice.edu"
        git config --global user.name "Linshengyi-William"

    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build

      
    - name: Deploy to GitHub Pages
      run: |
        echo "machine github.com login ${{ secrets.ACTIONS_DEPLOY_USERNAME }} password ${{ secrets.ACTIONS_DEPLOY_KEY }}" > ~/.netrc
        npm install -g gh-pages
        gh-pages -d build -o origin -b gh-pages-git-action-flow
      env:
        GH_TOKEN: ${{ secrets.ACTIONS_DEPLOY_KEY }}